### ISSUE TITLE
MathML stripped out upon HTML import

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pb-mathjax#17]
When a html file containing MathML is imported to Pressbooks using the html import routine, the MathML is stripped out or sanitized so that it no longer displays as expected. Users must instead copy/paste the html source into the text editor. Ideally, MathML would be able to pass through the import and ingestion routine unchanged.

**Comment by SteelWagstaff** [comment]
As an example, see this chapter of a Saylor book: https://saylordotorg.github.io/text_introductory-statistics/s06-01-three-popular-data-displays.html. It can be imported to PB using the HTML import routine, but the product looks like: https://university.pressbooks.pub/import/chapter/three-popular-data-displays/. Images are included, but MathML is not. If the user copy/pastes the source into Pressbooks, MathML works, but images (which have relative links) do not. See: https://integrations.pressbooks.network/testbookfun/chapter/three-popular-data-displays/

**Comment by dac514** [comment]
This is fixed with the slogan _"Not all imports are sanitized equal."_

+ Step 1: Filter quite strictly using HtmLawed, but [don't touch mixed markup (MathML)](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s3.9)
+ Step 2: Apply our WordPress `$allowedposttags`, `wp_filter_post_kses` [MathML rules](https://github.com/pressbooks/pressbooks/blob/348ccf17b4d9e949c324b0226a7b1b267c507393/inc/class-mathjax.php#L583).

The rules in Step 2 are based on WordPress role. The principle is the same as why superadmin can paste whatever HTML they want in TinyMCE, but an editor cannot.

Using [the example URL](https://saylordotorg.github.io/text_introductory-statistics/s06-01-three-popular-data-displays.html), super admin will import:

```html
<math xml:id="fwk-shafer-ch02-m0001" display="block">... snip ...
```

An editor:

```html
<math display="block">... snip ...
```

Synonym of technically, assuming [our custom MathML + kses rules are on purpose](https://github.com/pressbooks/pressbooks/blob/348ccf17b4d9e949c324b0226a7b1b267c507393/inc/class-mathjax.php#L583), there's no difference.

**Comment by mcgratay** [comment]
Resolved.
